# Generated by Django 5.2.5 on 2025-08-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('electrician', 'Electrician'), ('admin', 'Admin')], max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('experience_year', models.IntegerField(blank=True, null=True)),
                ('service_skill', models.TextField(blank=True, null=True)),
                ('service_km', models.IntegerField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, max_length=20, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('is_gov_verified', models.BooleanField(default=False)),
                ('is_police_verified', models.BooleanField(default=False)),
                ('is_admin_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('wallet_balance', models.FloatField(default=0.0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('is_default', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer.customerprofile')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
