# Generated by Django 5.2.5 on 2025-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerprofile_otp_customerprofile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
    ]
