# Generated by Django 5.2.5 on 2025-08-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('customer', '0004_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='service_categories', to='admin_panel.subcategory'),
        ),
    ]
