# Generated by Django 5.2.5 on 2025-08-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('customer', '0006_cart_servicecart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assign', 'Assigned'), ('arriving', 'Arriving'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='assign', max_length=20)),
                ('technician_required', models.IntegerField(default=1)),
                ('is_agency_booking', models.BooleanField(default=False)),
                ('is_manual_assignment', models.BooleanField(default=False)),
                ('manual_assignment_reason', models.TextField(blank=True, null=True)),
                ('manual_assignment_date', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('scheduled_date_time', models.DateTimeField(blank=True, null=True)),
                ('accept_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('quatation_amt', models.FloatField(default=0.0)),
                ('otp_required', models.BooleanField(default=True)),
                ('service_start_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], default='Approve', max_length=20)),
                ('job_started_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='job_photos/')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('is_bill_generated', models.BooleanField(default=False)),
                ('pdf_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_repeated', models.BooleanField(default=False)),
                ('triggered', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('assigned_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_bookings', to='customer.customerprofile')),
                ('assigned_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_assigned_jobs', to='customer.customerprofile')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='customer.customerprofile')),
                ('otp_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_verified_jobs', to='customer.customerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customer.customerprofile')),
            ],
        ),
    ]
