# Generated by Django 5.2.5 on 2025-08-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_servicebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('electrician', 'Electrician')], default='user', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('profile', 'Profile'), ('wallet', 'Wallet'), ('complaint', 'Complaint'), ('arrival', 'Arrival')], max_length=50)),
                ('channel', models.CharField(choices=[('app', 'App'), ('email', 'Email'), ('sms', 'SMS')], default='app', max_length=20)),
                ('is_sent', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('electrician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_notifications', to='customer.customerprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='customer.customerprofile')),
            ],
        ),
    ]
