# Generated by Django 5.2.5 on 2025-08-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('customer', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebook',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.subcategory'),
        ),
    ]
