# Generated by Django 5.2.5 on 2025-08-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_servicebook_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
