# Generated by Django 5.2.5 on 2025-08-21 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customerprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='electrician',
        ),
        migrations.AddField(
            model_name='notification',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_notifications', to='customer.customerprofile'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('service_provider', 'Service Provider'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('service_provider', 'Service Provider')], default='user', max_length=20),
        ),
    ]
