# Generated by Django 5.2.5 on 2025-08-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_notification_electrician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='company_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='customer.customerprofile')),
            ],
        ),
    ]
