# Generated by Django 5.2.5 on 2025-08-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_pendingprofileupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='pending_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
