# Generated by Django 5.2.5 on 2025-08-22 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_bankdetail_is_approved_bankdetail_pending_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetail',
            name='pending_data',
        ),
        migrations.CreateModel(
            name='PendingBankDetailUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('bank_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates', to='customer.bankdetail')),
            ],
        ),
    ]
