# Generated by Django 5.2.5 on 2025-08-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
