# Generated by Django 5.2.5 on 2025-08-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='service_covers/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='subcategory_image/'),
        ),
    ]
